<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Hotel;

class HotelSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        //

        Hotel::create(['userId' => 1, 'name' => 'Europa Hotel', 'image' => 'uploads/54t5D8F3isNy6XSXryrgBkg2jwIpGCg63exeaAqo.jpg', 'address' => 'Gt Victoria Street', 'town' => 'Belfast', 'country' => 'N. Ireland', 'postCode' => 'BT1 1XX', 'accomType' => 'Hotel', 'roomType' => 'Single', 'holidayType' => 'City Break', 'stars' => 'three', 'feat1' => 'Add breakfast', 'feat2' => 'Add dinner', 'feat3' => 'Add lunch', 'feat4' => 'Add activity', 'feat1Price' => 10, 'feat2Price' => 20, 'feat3Price' => 15, 'feat4Price' => 20, 'upgrade1' => 'Penthouse Suite', 'upgrade2' => 'Add Balcony', 'upgrade3' => 'Large Room', 'upgrade1price' => 100, 'upgrade2price' => 150, 'upgrade3price' => 100, 'package1' => 'Bridal Package', 'package2' => 'Family Package', 'package3' => 'Unlimited Drinks', 'package1price' => 300, 'package2price' => 200, 'package3price' => 100, 'currency' => 'Sterling', 'price' => 200, 'numRooms' => 3, 'description' => 'Great city hotel', 'agreeTerms' => 1]);

        Hotel::create(['userId' => 1, 'name' => 'Amsterdam Beach Hotel', 'image' => 'uploads/laFDUIHlizM0lha2v84NLnXDig24iuFZ600a4Sj7.jpg', 'address' => '1a Main Street', 'town' => 'Zandvoort', 'country' => 'Netherlands', 'postCode' => 'ZN1 1XX', 'accomType' => 'Hotel', 'roomType' => 'Single', 'holidayType' => 'Seaside Resort', 'stars' => 'three', 'feat1' => 'Add breakfast', 'feat2' => 'Add dinner', 'feat3' => 'Add lunch', 'feat4' => 'Add activity', 'feat1Price' => 10, 'feat2Price' => 20, 'feat3Price' => 15, 'feat4Price' => 20, 'upgrade1' => 'Penthouse Suite', 'upgrade2' => 'Add Balcony', 'upgrade3' => 'Large Room', 'upgrade1price' => 100, 'upgrade2price' => 150, 'upgrade3price' => 100, 'package1' => 'Bridal Package', 'package2' => 'Family Package', 'package3' => 'Unlimited Drinks', 'package1price' => 300, 'package2price' => 200, 'package3price' => 100, 'currency' => 'Sterling', 'price' => 200, 'numRooms' => 3, 'description' => 'Great beach hotel', 'agreeTerms' => 1]);

        Hotel::create(['userId' => 1, 'name' => 'Lake of Shadows', 'image' => 'uploads/esyzxLSWp3alucJmRgjVoo6obtQ3yYu2OgGO2bAX.jpg', 'address' => '1a Main Street', 'town' => 'Buncrana', 'country' => 'Ireland', 'postCode' => 'BN1 1XX', 'accomType' => 'Hotel', 'roomType' => 'Triple', 'holidayType' => 'Country Escape', 'stars' => 'three', 'feat1' => 'Add breakfast', 'feat2' => 'Add dinner', 'feat3' => 'Add lunch', 'feat4' => 'Add activity', 'feat1Price' => 10, 'feat2Price' => 20, 'feat3Price' => 15, 'feat4Price' => 20, 'upgrade1' => 'Penthouse Suite', 'upgrade2' => 'Add Balcony', 'upgrade3' => 'Large Room', 'upgrade1price' => 100, 'upgrade2price' => 150, 'upgrade3price' => 100, 'package1' => 'Bridal Package', 'package2' => 'Family Package', 'package3' => 'Unlimited Drinks', 'package1price' => 300, 'package2price' => 200, 'package3price' => 100, 'currency' => 'Sterling', 'price' => 400, 'numRooms' => 3, 'description' => 'Great country hotel', 'agreeTerms' => 1]);

        Hotel::create(['userId' => 1, 'name' => 'Slieve Donard', 'image' => 'uploads/sv1u2EBzJDR7WUiAHECykXlUu3pXAzxnW9fWRmd9.jpg', 'address' => 'Gt Victoria Street', 'town' => 'Newcastle', 'country' => 'N. Ireland', 'postCode' => 'NW1 1XX', 'accomType' => 'Hotel', 'roomType' => 'Double', 'holidayType' => 'Seaside Resort', 'stars' => 'four', 'feat1' => 'Add breakfast', 'feat2' => 'Add dinner', 'feat3' => 'Add lunch', 'feat4' => 'Add activity', 'feat1Price' => 10, 'feat2Price' => 20, 'feat3Price' => 15, 'feat4Price' => 20, 'upgrade1' => 'Penthouse Suite', 'upgrade2' => 'Add Balcony', 'upgrade3' => 'Large Room', 'upgrade1price' => 100, 'upgrade2price' => 150, 'upgrade3price' => 100, 'package1' => 'Bridal Package', 'package2' => 'Family Package', 'package3' => 'Unlimited Drinks', 'package1price' => 300, 'package2price' => 200, 'package3price' => 100, 'currency' => 'Sterling', 'price' => 300, 'numRooms' => 1, 'description' => 'Great beach hotel', 'agreeTerms' => 1]);

        Hotel::create(['userId' => 1, 'name' => 'Sunset Beach Club', 'image' => 'uploads/iEFokUmxwatFFGmM5tu7WaEWi9gzy7vG5VLut4yt.jpg', 'address' => '1a Main Street', 'town' => 'Benalmadena', 'country' => 'Spain', 'postCode' => 'ZN1 1XX', 'accomType' => 'Hotel', 'roomType' => 'Twin', 'holidayType' => 'Seaside Resort', 'stars' => 'five', 'feat1' => 'Add breakfast', 'feat2' => 'Add dinner', 'feat3' => 'Add lunch', 'feat4' => 'Add activity', 'feat1Price' => 10, 'feat2Price' => 20, 'feat3Price' => 15, 'feat4Price' => 20, 'upgrade1' => 'Penthouse Suite', 'upgrade2' => 'Add Balcony', 'upgrade3' => 'Large Room', 'upgrade1price' => 100, 'upgrade2price' => 150, 'upgrade3price' => 100, 'package1' => 'Bridal Package', 'package2' => 'Family Package', 'package3' => 'Unlimited Drinks', 'package1price' => 300, 'package2price' => 200, 'package3price' => 100, 'currency' => 'Sterling', 'price' => 250, 'numRooms' => 8, 'description' => 'Great beach hotel', 'agreeTerms' => 1]);

        Hotel::create(['userId' => 1, 'name' => 'Cyprus Villa', 'image' => 'uploads/2qs16i73nrs8kDCxGjEx9wcdSkEtOygeodyZCPCl.jpg', 'address' => '1a Main Street', 'town' => 'Buncrana', 'country' => 'Ireland', 'postCode' => 'BN1 1XX', 'accomType' => 'Villa', 'roomType' => 'Family Room', 'holidayType' => 'Country Escape', 'stars' => 'three', 'feat1' => 'Add breakfast', 'feat2' => 'Add dinner', 'feat3' => 'Add lunch', 'feat4' => 'Add activity', 'feat1Price' => 10, 'feat2Price' => 20, 'feat3Price' => 15, 'feat4Price' => 20, 'upgrade1' => 'Penthouse Suite', 'upgrade2' => 'Add Balcony', 'upgrade3' => 'Large Room', 'upgrade1price' => 100, 'upgrade2price' => 150, 'upgrade3price' => 100, 'package1' => 'Bridal Package', 'package2' => 'Family Package', 'package3' => 'Unlimited Drinks', 'package1price' => 300, 'package2price' => 200, 'package3price' => 100, 'currency' => 'Sterling', 'price' => 300, 'numRooms' => 1, 'description' => 'Great holiday villa', 'agreeTerms' => 1]);
    }
}
